"""Real-byte test fixtures.

Two tiers, because two different things need proving and only one of them can
live in an open-source repository:

- **Tier 1**, ``corpus/`` — ``.rm`` pages and their ``.content`` / ``.metadata``
  sidecars, generated by :mod:`tests.fixtures.build_corpus` and committed as
  frozen bytes. Synthetic, kilobytes, no personal data, runs everywhere.
- **Tier 2**, ``~/.local/share/living-ink/test-corpus/`` — a read-only capture
  of the real tablet, written by ``scripts/capture_corpus.py``. Never
  committed; tests that want it skip when it is absent.

Both tiers are the same on-disk shape — a xochitl directory — so
:class:`tests.fixtures.transport.CorpusTransport` serves either.
"""

from tests.fixtures.builders import (
    AUTHOR_UUID,
    DocumentSpec,
    FolderSpec,
    Layer,
    PageSpec,
    point,
    stroke,
    write_document,
    write_folder,
    write_rm,
)
from tests.fixtures.transport import (
    CorpusTransport,
    FakeSSHRunner,
    UnsupportedCorpusTransport,
)

__all__ = [
    "AUTHOR_UUID",
    "CorpusTransport",
    "DocumentSpec",
    "FakeSSHRunner",
    "FolderSpec",
    "Layer",
    "PageSpec",
    "UnsupportedCorpusTransport",
    "point",
    "stroke",
    "write_document",
    "write_folder",
    "write_rm",
]
