"""Generate the committed fixture corpus.

Run as ``python -m tests.fixtures.build_corpus`` to rewrite
``tests/fixtures/corpus/``. The output is committed as frozen bytes and is
**not** regenerated by the test suite: a fixture rebuilt by the installed
``rmscene`` moves whenever ``rmscene`` moves, and that drift is exactly what
these files exist to detect.

The corpus is a xochitl-shaped directory, the same shape a real device capture
has, so :class:`tests.fixtures.transport.CorpusTransport` serves either one.

Every document here is synthetic. Nothing in the corpus came off anybody's
tablet, which is what makes it safe to commit to an open-source repository.
"""

from __future__ import annotations

import io
import zipfile
from pathlib import Path
from typing import List

from rmscene import scene_items as si

from tests.fixtures.builders import (
    DocumentSpec,
    FolderSpec,
    Layer,
    PageSpec,
    stroke,
    truncated_rm_bytes,
    unsupported_version_bytes,
    write_document,
    write_folder,
)

#: Where the committed corpus lives.
CORPUS_DIR = Path(__file__).parent / "corpus"

# Fixed UUIDs. A fixture's id is part of its identity — it lands in the state
# store, in Obsidian frontmatter and in cache keys — so these are pinned rather
# than generated.
FOLDER_ROOT = "10000000-0000-4000-8000-000000000001"
FOLDER_NESTED = "10000000-0000-4000-8000-000000000002"
FOLDER_DEEP = "10000000-0000-4000-8000-000000000003"

DOC_HANDWRITTEN = "20000000-0000-4000-8000-000000000001"
DOC_BLANK_MIDDLE = "20000000-0000-4000-8000-000000000002"
DOC_LAYERS = "20000000-0000-4000-8000-000000000003"
DOC_TYPED = "20000000-0000-4000-8000-000000000004"
DOC_TRUNCATED = "20000000-0000-4000-8000-000000000005"
DOC_FUTURE_VERSION = "20000000-0000-4000-8000-000000000006"
DOC_LONG = "20000000-0000-4000-8000-000000000007"
DOC_HOSTILE_TITLE = "20000000-0000-4000-8000-000000000008"
DOC_UNICODE_TITLE = "20000000-0000-4000-8000-000000000009"
DOC_TAGGED = "20000000-0000-4000-8000-00000000000a"
DOC_TRASHED = "20000000-0000-4000-8000-00000000000b"
DOC_DELETED_PAGE = "20000000-0000-4000-8000-00000000000c"
DOC_PDF = "20000000-0000-4000-8000-00000000000d"
DOC_EPUB = "20000000-0000-4000-8000-00000000000e"
DOC_NESTED = "20000000-0000-4000-8000-00000000000f"


def _page_id(doc_id: str, index: int) -> str:
    """Derive a stable page UUID from its document and position.

    Args:
        doc_id: The owning document's UUID.
        index: Zero-based page position.

    Returns:
        A UUID-shaped string unique to that page.
    """
    return f"{doc_id[:24]}{index:012x}"


def _letter_h() -> List[si.Line]:
    """Return strokes drawing a large letter H.

    Something legible matters: a render regression that turns ink into noise is
    obvious in a letter and invisible in a scribble.

    Returns:
        Three strokes forming an H.
    """
    return [
        stroke([(-300, 200), (-300, 500)]),
        stroke([(-300, 350), (-150, 350)]),
        stroke([(-150, 200), (-150, 500)]),
    ]


def _letter_i() -> List[si.Line]:
    """Return strokes drawing a large letter I.

    Returns:
        Three strokes forming a serifed I.
    """
    return [
        stroke([(50, 200), (200, 200)]),
        stroke([(125, 200), (125, 500)]),
        stroke([(50, 500), (200, 500)]),
    ]


#: Text drawn on each generated PDF page. ``{page}`` is the 1-based number.
PDF_LINES = (
    "Fixture PDF page {page}",
    "The quick brown fox jumps over the lazy dog.",
)


def _minimal_pdf(pages: int = 2) -> bytes:
    """Build a small valid PDF with selectable text.

    Assembled by hand rather than by PyMuPDF because PyMuPDF writes a ``/ID``
    derived from the save, so two identical documents differ byte for byte and
    the fixture could never be committed as frozen bytes.

    Args:
        pages: How many pages to emit.

    Returns:
        The PDF bytes.
    """
    kids = " ".join(f"{4 + i * 2} 0 R" for i in range(pages))
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        f"<< /Type /Pages /Kids [{kids}] /Count {pages} >>".encode(),
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    for number in range(pages):
        objects.append(
            (
                f"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] "
                f"/Resources << /Font << /F1 3 0 R >> >> "
                f"/Contents {5 + number * 2} 0 R >>"
            ).encode()
        )
        text = "".join(
            f"BT /F1 12 Tf 72 {760 - 30 * index} Td ({line.format(page=number + 1)}) Tj ET\n"
            for index, line in enumerate(PDF_LINES)
        ).encode()
        objects.append(b"<< /Length %d >>\nstream\n" % len(text) + text + b"endstream")

    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for index, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += b"%d 0 obj\n" % index + body + b"\nendobj\n"

    xref = len(out)
    out += b"xref\n0 %d\n0000000000 65535 f \n" % (len(objects) + 1)
    for offset in offsets:
        out += b"%010d 00000 n \n" % offset
    out += b"trailer\n<< /Size %d /Root 1 0 R >>\nstartxref\n%d\n%%%%EOF\n" % (
        len(objects) + 1,
        xref,
    )
    return bytes(out)


def _minimal_epub() -> bytes:
    """Build a small valid EPUB.

    Hand-assembled rather than produced by ``ebooklib`` so the bytes are
    deterministic: the library stamps a modification time into the OPF.

    Returns:
        The EPUB bytes.
    """
    container = (
        '<?xml version="1.0"?>'
        '<container version="1.0" '
        'xmlns="urn:oasis:names:tc:opendocument:xmlns:container">'
        '<rootfiles><rootfile full-path="OEBPS/content.opf" '
        'media-type="application/oebps-package+xml"/></rootfiles></container>'
    )
    opf = (
        '<?xml version="1.0"?>'
        '<package xmlns="http://www.idpf.org/2007/opf" version="3.0" '
        'unique-identifier="bookid">'
        '<metadata xmlns:dc="http://purl.org/dc/elements/1.1/">'
        '<dc:identifier id="bookid">living-ink-fixture</dc:identifier>'
        "<dc:title>Fixture Book</dc:title><dc:language>en</dc:language>"
        "</metadata>"
        '<manifest><item id="c1" href="chapter1.xhtml" '
        'media-type="application/xhtml+xml"/></manifest>'
        '<spine><itemref idref="c1"/></spine></package>'
    )
    chapter = (
        '<?xml version="1.0" encoding="utf-8"?>'
        '<html xmlns="http://www.w3.org/1999/xhtml"><head>'
        "<title>Chapter One</title></head><body>"
        "<h1>Chapter One</h1>"
        "<p>The quick brown fox jumps over the lazy dog.</p>"
        "</body></html>"
    )

    # A zip entry carries a modification time, which defaults to the clock and
    # would make the fixture differ on every build. Pin it to the epoch the
    # format starts at.
    def entry(name: str) -> zipfile.ZipInfo:
        info = zipfile.ZipInfo(name)
        info.date_time = (1980, 1, 1, 0, 0, 0)
        return info

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w") as archive:
        # The mimetype entry must be first and stored uncompressed.
        archive.writestr(
            entry("mimetype"),
            "application/epub+zip",
            compress_type=zipfile.ZIP_STORED,
        )
        archive.writestr(entry("META-INF/container.xml"), container)
        archive.writestr(entry("OEBPS/content.opf"), opf)
        archive.writestr(entry("OEBPS/chapter1.xhtml"), chapter)
    return buffer.getvalue()


def build(root: Path = CORPUS_DIR) -> Path:
    """Write the whole corpus.

    Args:
        root: Destination directory. Created if absent; existing fixture files
            are overwritten.

    Returns:
        The corpus directory.
    """
    root.mkdir(parents=True, exist_ok=True)

    write_folder(root, FolderSpec(FOLDER_ROOT, "Fixtures"))
    write_folder(root, FolderSpec(FOLDER_NESTED, "Nested", parent=FOLDER_ROOT))
    write_folder(root, FolderSpec(FOLDER_DEEP, "Deeper", parent=FOLDER_NESTED))

    # A single handwritten page. The baseline for render and OCR tests.
    write_document(
        root,
        DocumentSpec(
            DOC_HANDWRITTEN,
            "handwritten",
            [PageSpec(_page_id(DOC_HANDWRITTEN, 0), template="P Margin small")],
            parent=FOLDER_ROOT,
        ),
        pages=[[Layer("Layer 1", _letter_h())]],
    )

    # Ink, nothing, ink. The `sync.skip_empty` predicate has to tell this from a
    # notebook whose pages all came back empty because the provider rate-limited.
    write_document(
        root,
        DocumentSpec(
            DOC_BLANK_MIDDLE,
            "blank page in the middle",
            [PageSpec(_page_id(DOC_BLANK_MIDDLE, i)) for i in range(3)],
            parent=FOLDER_ROOT,
        ),
        pages=[[Layer("Layer 1", _letter_h())], [], [Layer("Layer 1", _letter_i())]],
    )

    # Two layers, a highlighter and an eraser stroke.
    write_document(
        root,
        DocumentSpec(
            DOC_LAYERS,
            "layers and highlighter",
            [PageSpec(_page_id(DOC_LAYERS, 0))],
            parent=FOLDER_ROOT,
        ),
        pages=[
            [
                Layer("Layer 1", _letter_h()),
                Layer(
                    "Highlight",
                    [
                        stroke(
                            [(-320, 350), (-130, 350)],
                            tool=si.Pen.HIGHLIGHTER_2,
                            color=si.PenColor.HIGHLIGHT,
                            width=60,
                        )
                    ],
                ),
                Layer(
                    "Corrections",
                    [stroke([(-200, 600), (-100, 600)], tool=si.Pen.ERASER, width=40)],
                ),
            ]
        ],
    )

    # Typed text, as the keyboard and Type Folio produce: a RootTextBlock and no
    # strokes at all.
    write_document(
        root,
        DocumentSpec(
            DOC_TYPED,
            "typed text",
            [PageSpec(_page_id(DOC_TYPED, 0))],
            parent=FOLDER_ROOT,
        ),
        texts=["Typed rather than handwritten.\nSecond line."],
    )

    # A page that stops mid-block, and a page from a firmware this build cannot
    # read. Both must fail loudly rather than publish an empty note.
    write_document(
        root,
        DocumentSpec(
            DOC_TRUNCATED,
            "truncated page",
            [PageSpec(_page_id(DOC_TRUNCATED, 0))],
            parent=FOLDER_ROOT,
        ),
    )
    truncated_rm_bytes(root / DOC_TRUNCATED / f"{_page_id(DOC_TRUNCATED, 0)}.rm")

    write_document(
        root,
        DocumentSpec(
            DOC_FUTURE_VERSION,
            "format version 7",
            [PageSpec(_page_id(DOC_FUTURE_VERSION, 0))],
            parent=FOLDER_ROOT,
        ),
    )
    unsupported_version_bytes(root / DOC_FUTURE_VERSION / f"{_page_id(DOC_FUTURE_VERSION, 0)}.rm")

    # Enough pages that `ocr_concurrency` is doing something, and that a test can
    # assert results come back in page order regardless of completion order.
    long_pages = [PageSpec(_page_id(DOC_LONG, i)) for i in range(60)]
    write_document(
        root,
        DocumentSpec(DOC_LONG, "sixty pages", long_pages, parent=FOLDER_ROOT),
        pages=[[Layer("Layer 1", [stroke([(-300, 200 + i), (300, 400 + i)])])] for i in range(60)],
    )

    # Titles a filesystem will not take verbatim. The adversarial inputs live in
    # the S1 table test; these are what a user actually types.
    write_document(
        root,
        DocumentSpec(
            DOC_HOSTILE_TITLE,
            'Q1 2026/Review: "draft" <v2>',
            [PageSpec(_page_id(DOC_HOSTILE_TITLE, 0))],
            parent=FOLDER_ROOT,
        ),
        pages=[[Layer("Layer 1", _letter_h())]],
    )
    write_document(
        root,
        DocumentSpec(
            DOC_UNICODE_TITLE,
            "Café ☕ notes — draft ",
            [PageSpec(_page_id(DOC_UNICODE_TITLE, 0))],
            parent=FOLDER_ROOT,
        ),
        pages=[[Layer("Layer 1", _letter_i())]],
    )

    # A document tag and a page tag, on different pages.
    tagged_pages = [PageSpec(_page_id(DOC_TAGGED, i)) for i in range(2)]
    write_document(
        root,
        DocumentSpec(
            DOC_TAGGED,
            "tagged notebook",
            tagged_pages,
            parent=FOLDER_ROOT,
            tags=["project", "reading list"],
            page_tags=[(tagged_pages[1].page_id, "follow-up")],
        ),
        pages=[[Layer("Layer 1", _letter_h())], [Layer("Layer 1", _letter_i())]],
    )

    # In the trash. Present in a full listing, absent from a sync, and the input
    # to orphan handling.
    write_document(
        root,
        DocumentSpec(
            DOC_TRASHED,
            "thrown away",
            [PageSpec(_page_id(DOC_TRASHED, 0))],
            parent="trash",
            deleted=True,
        ),
        pages=[[Layer("Layer 1", _letter_h())]],
    )

    # A page the user removed stays in cPages with a marker. Page two of three
    # is gone, so a reader that ignores the marker publishes a page that is not
    # on the tablet.
    deleted_pages = [PageSpec(_page_id(DOC_DELETED_PAGE, i)) for i in range(3)]
    deleted_pages[1].deleted = True
    write_document(
        root,
        DocumentSpec(
            DOC_DELETED_PAGE,
            "page two removed",
            deleted_pages,
            parent=FOLDER_ROOT,
        ),
        pages=[
            [Layer("Layer 1", _letter_h())],
            [Layer("Layer 1", _letter_i())],
            [Layer("Layer 1", _letter_h())],
        ],
    )

    # An annotated PDF and an annotated EPUB: one .rm layer over a source file.
    write_document(
        root,
        DocumentSpec(
            DOC_PDF,
            "annotated pdf",
            [PageSpec(_page_id(DOC_PDF, i)) for i in range(2)],
            parent=FOLDER_ROOT,
            file_type="pdf",
        ),
        pages=[[Layer("Layer 1", _letter_h())], []],
        raw_file=("pdf", _minimal_pdf(pages=2)),
    )
    write_document(
        root,
        DocumentSpec(
            DOC_EPUB,
            "annotated epub",
            [PageSpec(_page_id(DOC_EPUB, 0))],
            parent=FOLDER_ROOT,
            file_type="epub",
        ),
        pages=[[Layer("Layer 1", _letter_i())]],
        raw_file=("epub", _minimal_epub()),
    )

    # Three folders deep, so the destination's folder mirroring has a tree to
    # mirror rather than one flat directory.
    write_document(
        root,
        DocumentSpec(
            DOC_NESTED,
            "buried three deep",
            [PageSpec(_page_id(DOC_NESTED, 0))],
            parent=FOLDER_DEEP,
        ),
        pages=[[Layer("Layer 1", _letter_h())]],
    )

    return root


if __name__ == "__main__":  # pragma: no cover - developer entry point
    written = build()
    count = len(list(written.glob("*.metadata")))
    print(f"Wrote {count} items to {written}")
